[package]
name = "money"
version = "0.1.0"
authors = ["Richard Bone <rjonbone@gmail.com>"]
description = "A simple money handling library"
license-file = "LICENSE"
repository = "https://github.com/rbone/rust-money"
homepage = "https://github.com/rbone/rust-money"


[dependencies]
